name: StructuresCraftable
version: ${project.version}
main: cf.itoncek.deathstructure.DeathStructure
api-version: 1.16
authors: [ notnotnotswipez ]
commands:
  giveallstructures:
    usage: §c/giveallstructures
